// <auto-generated />
namespace RecipeService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class MeasurementUnit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeasurementUnit));
        
        string IMigrationMetadata.Id
        {
            get { return "201502081134512_MeasurementUnit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
