// <auto-generated />
namespace RecipeService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class DailyValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DailyValues));
        
        string IMigrationMetadata.Id
        {
            get { return "201502081640405_DailyValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
