//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34014
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/recipeSummary.xsd")]
[System.Xml.Serialization.XmlRootAttribute("recipeSummary", Namespace="http://tempuri.org/recipeSummary.xsd", IsNullable=false)]
public partial class RecipeSummary {
    
    private Ingredient[] ingredientsField;
    
    private NutritionFact[] nutritionFactsField;
    
    private DailyValues dailyValuesField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ingredient", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Ingredient[] ingredients {
        get {
            return this.ingredientsField;
        }
        set {
            this.ingredientsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("nutrition-fact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NutritionFact[] nutritionFacts {
        get {
            return this.nutritionFactsField;
        }
        set {
            this.nutritionFactsField = value;
        }
    }
    
    /// <uwagi/>
    public DailyValues dailyValues {
        get {
            return this.dailyValuesField;
        }
        set {
            this.dailyValuesField = value;
        }
    }
}
