//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34014
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/recipeSummary.xsd")]
[System.Xml.Serialization.XmlRootAttribute("recipe-summary", Namespace="http://tempuri.org/recipeSummary.xsd", IsNullable=false)]
public partial class RecipeSummary {
    
    private Ingredient[] ingredientsField;
    
    private NutritionFact[] nutritionfactsField;
    
    private DailyValues dailyvaluesField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ingredient", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Ingredient[] ingredients {
        get {
            return this.ingredientsField;
        }
        set {
            this.ingredientsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayAttribute("nutrition-facts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("nutrition-fact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NutritionFact[] nutritionfacts {
        get {
            return this.nutritionfactsField;
        }
        set {
            this.nutritionfactsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("daily-values", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DailyValues dailyvalues {
        get {
            return this.dailyvaluesField;
        }
        set {
            this.dailyvaluesField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/recipes")]
public partial class Ingredient {
    
    private string nameField;
    
    private decimal quantityField;
    
    private MeasurementUnit unitsField;
    
    private int factIdField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MeasurementUnit units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int factId {
        get {
            return this.factIdField;
        }
        set {
            this.factIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/recipes")]
public enum MeasurementUnit {
    
    /// <uwagi/>
    kg,
    
    /// <uwagi/>
    dag,
    
    /// <uwagi/>
    g,
    
    /// <uwagi/>
    mg,
    
    /// <uwagi/>
    oz,
    
    /// <uwagi/>
    lb,
    
    /// <uwagi/>
    l,
    
    /// <uwagi/>
    ml,
    
    /// <uwagi/>
    tsp,
    
    /// <uwagi/>
    tbsp,
    
    /// <uwagi/>
    cup,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public partial class DailyValues {
    
    private Fats fatsField;
    
    private Calories caloriesField;
    
    private Carbohydrates carbohydratesField;
    
    private Minerals mineralsField;
    
    private Proteins proteinsField;
    
    private Vitamins vitaminsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Fats fats {
        get {
            return this.fatsField;
        }
        set {
            this.fatsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Calories calories {
        get {
            return this.caloriesField;
        }
        set {
            this.caloriesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Carbohydrates carbohydrates {
        get {
            return this.carbohydratesField;
        }
        set {
            this.carbohydratesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Minerals minerals {
        get {
            return this.mineralsField;
        }
        set {
            this.mineralsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Proteins proteins {
        get {
            return this.proteinsField;
        }
        set {
            this.proteinsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Vitamins vitamins {
        get {
            return this.vitaminsField;
        }
        set {
            this.vitaminsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public partial class Fats {
    
    private decimal saturatedfatField;
    
    private decimal monounsaturatedfatField;
    
    private decimal polyunsaturatedfatField;
    
    private WeightUnit unitsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("saturated-fat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal saturatedfat {
        get {
            return this.saturatedfatField;
        }
        set {
            this.saturatedfatField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("monounsaturated-fat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal monounsaturatedfat {
        get {
            return this.monounsaturatedfatField;
        }
        set {
            this.monounsaturatedfatField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("polyunsaturated-fat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal polyunsaturatedfat {
        get {
            return this.polyunsaturatedfatField;
        }
        set {
            this.polyunsaturatedfatField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WeightUnit units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public enum WeightUnit {
    
    /// <uwagi/>
    kg,
    
    /// <uwagi/>
    dag,
    
    /// <uwagi/>
    g,
    
    /// <uwagi/>
    mg,
    
    /// <uwagi/>
    oz,
    
    /// <uwagi/>
    lb,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public partial class Calories {
    
    private decimal fromcarbohydrateField;
    
    private decimal fromfatField;
    
    private decimal fromproteinField;
    
    private EnergyUnit unitsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("from-carbohydrate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal fromcarbohydrate {
        get {
            return this.fromcarbohydrateField;
        }
        set {
            this.fromcarbohydrateField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("from-fat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal fromfat {
        get {
            return this.fromfatField;
        }
        set {
            this.fromfatField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("from-protein", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal fromprotein {
        get {
            return this.fromproteinField;
        }
        set {
            this.fromproteinField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public EnergyUnit units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public enum EnergyUnit {
    
    /// <uwagi/>
    kJ,
    
    /// <uwagi/>
    kcal,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public partial class Carbohydrates {
    
    private decimal dietaryfiberField;
    
    private decimal sugarsField;
    
    private WeightUnit unitsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("dietary-fiber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal dietaryfiber {
        get {
            return this.dietaryfiberField;
        }
        set {
            this.dietaryfiberField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal sugars {
        get {
            return this.sugarsField;
        }
        set {
            this.sugarsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WeightUnit units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public partial class Minerals {
    
    private decimal calciumField;
    
    private decimal ironField;
    
    private decimal magnesiumField;
    
    private decimal potassiumField;
    
    private decimal sodiumField;
    
    private WeightUnit unitsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Calcium {
        get {
            return this.calciumField;
        }
        set {
            this.calciumField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Iron {
        get {
            return this.ironField;
        }
        set {
            this.ironField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Magnesium {
        get {
            return this.magnesiumField;
        }
        set {
            this.magnesiumField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Potassium {
        get {
            return this.potassiumField;
        }
        set {
            this.potassiumField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Sodium {
        get {
            return this.sodiumField;
        }
        set {
            this.sodiumField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WeightUnit units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public partial class Proteins {
    
    private WeightUnit unitsField;
    
    private decimal valueField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WeightUnit units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public partial class Vitamins {
    
    private decimal aField;
    
    private decimal cField;
    
    private decimal dField;
    
    private decimal eField;
    
    private WeightUnit unitsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal A {
        get {
            return this.aField;
        }
        set {
            this.aField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal C {
        get {
            return this.cField;
        }
        set {
            this.cField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal D {
        get {
            return this.dField;
        }
        set {
            this.dField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal E {
        get {
            return this.eField;
        }
        set {
            this.eField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WeightUnit units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public partial class NutritionFact {
    
    private string foodnameField;
    
    private Fats fatsField;
    
    private Calories caloriesField;
    
    private Carbohydrates carbohydratesField;
    
    private Minerals mineralsField;
    
    private Proteins proteinsField;
    
    private Vitamins vitaminsField;
    
    private int idField;
    
    private decimal quantityField;
    
    private MeasurementUnit1 unitsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("food-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string foodname {
        get {
            return this.foodnameField;
        }
        set {
            this.foodnameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Fats fats {
        get {
            return this.fatsField;
        }
        set {
            this.fatsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Calories calories {
        get {
            return this.caloriesField;
        }
        set {
            this.caloriesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Carbohydrates carbohydrates {
        get {
            return this.carbohydratesField;
        }
        set {
            this.carbohydratesField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Minerals minerals {
        get {
            return this.mineralsField;
        }
        set {
            this.mineralsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Proteins proteins {
        get {
            return this.proteinsField;
        }
        set {
            this.proteinsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Vitamins vitamins {
        get {
            return this.vitaminsField;
        }
        set {
            this.vitaminsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MeasurementUnit1 units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="MeasurementUnit", Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
public enum MeasurementUnit1 {
    
    /// <uwagi/>
    kg,
    
    /// <uwagi/>
    dag,
    
    /// <uwagi/>
    g,
    
    /// <uwagi/>
    mg,
    
    /// <uwagi/>
    oz,
    
    /// <uwagi/>
    lb,
    
    /// <uwagi/>
    l,
    
    /// <uwagi/>
    ml,
    
    /// <uwagi/>
    tsp,
    
    /// <uwagi/>
    tbsp,
    
    /// <uwagi/>
    cup,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/recipes")]
[System.Xml.Serialization.XmlRootAttribute("recipes", Namespace="http://students.mimuw.edu.pl/~cl320813/recipes", IsNullable=false)]
public partial class Recipes {
    
    private Recipe[] recipeField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("recipe", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Recipe[] recipe {
        get {
            return this.recipeField;
        }
        set {
            this.recipeField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/recipes")]
public partial class Recipe {
    
    private string titleField;
    
    private PreparationTime preparationTimeField;
    
    private int portionsField;
    
    private Ingredient[] ingredientsField;
    
    private RecipeSection[] contentField;
    
    private int idField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PreparationTime preparationTime {
        get {
            return this.preparationTimeField;
        }
        set {
            this.preparationTimeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int portions {
        get {
            return this.portionsField;
        }
        set {
            this.portionsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ingredient", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Ingredient[] ingredients {
        get {
            return this.ingredientsField;
        }
        set {
            this.ingredientsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("section", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public RecipeSection[] content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/recipes")]
public partial class PreparationTime {
    
    private TimeUnit unitsField;
    
    private bool unitsFieldSpecified;
    
    private decimal valueField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TimeUnit units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool unitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/recipes")]
public enum TimeUnit {
    
    /// <uwagi/>
    h,
    
    /// <uwagi/>
    min,
    
    /// <uwagi/>
    s,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/recipes")]
public partial class RecipeSection {
    
    private string nameField;
    
    private string[] textField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts")]
[System.Xml.Serialization.XmlRootAttribute("nutritionData", Namespace="http://students.mimuw.edu.pl/~cl320813/nutritionFacts", IsNullable=false)]
public partial class NutritionData {
    
    private NutritionFact[] nutritionfactsField;
    
    private DailyValues dailyvaluesField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayAttribute("nutrition-facts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("nutrition-fact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public NutritionFact[] nutritionfacts {
        get {
            return this.nutritionfactsField;
        }
        set {
            this.nutritionfactsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("daily-values", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DailyValues dailyvalues {
        get {
            return this.dailyvaluesField;
        }
        set {
            this.dailyvaluesField = value;
        }
    }
}
