//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34014
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/recipeSummary.xsd")]
[System.Xml.Serialization.XmlRootAttribute("recipe-summary", Namespace = "http://tempuri.org/recipeSummary.xsd", IsNullable = false)]
public partial class RecipeSummary
{

    private List<Ingredient> ingredientsField;

    private List<NutritionFact> nutritionFactsField;

    private DailyValues dailyValuesField;

    /// <uwagi/>
    [XmlArray("ingredients", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ingredient", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public List<Ingredient> Ingredients
    {
        get
        {
            return this.ingredientsField;
        }
        set
        {
            this.ingredientsField = value;
        }
    }

    /// <uwagi/>
    [XmlArray("nutrition-facts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("nutrition-fact", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public List<NutritionFact> NutritionFacts
    {
        get
        {
            return this.nutritionFactsField;
        }
        set
        {
            this.nutritionFactsField = value;
        }
    }

    /// <uwagi/>
    [XmlElement("daily-values", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DailyValues DailyValues
    {
        get
        {
            return this.dailyValuesField;
        }
        set
        {
            this.dailyValuesField = value;
        }
    }
}
